### ISSUE TITLE
Encoder problem

### ISSUE THREAD

**Issue by fred-dev** [Ushio/ofxExtremeGpuVideo#1]
I cannot get the encoders (batch or one shot) to recognise any videos on mac or windows. I have tried inputting a variety of video files via drag and drop as it is implemented in the code. I did leave the system for a few minutes, is this process very slow- should I wait longer?

Maybe I am starting with an incompatible codec? I have tried proress, hap and H264 on both platforms. It would be great to be able to see the potential of this code.

Cheers

**Comment by Ushio** [comment]
hello,
batch or one shot converter not support movie input. only image sequence.
so, please use "scripts/video_to_gvintermediate.rb" or "scripts/video_to_seq_all.rb" for video to image sequence.
Or, aftereffects can export image sequence.

Thanks.
