### ISSUE TITLE
Embedding in WPF / C# 

### ISSUE THREAD

**Issue by antithing** [Ushio/ofxExtremeGpuVideo#5]
Hi, and thank you for making this code available. i am trying to convert the Unity C# to run in a C# WPF application, and have hit a wall getting the texture buffer into a display-able image format. i am using:

```
public Image UpdateTexture(int frameAt)
		{
			var block = _lz4Blocks[frameAt];
			_filestream.Seek((long)block.address, SeekOrigin.Begin);
			_filestream.Read(_lz4Buffer, 0, (int)block.size);
			Marshal.Copy(_lz4Buffer, 0, _lz4BufferNative, (int)block.size);
			Lz4Native.lz4_decompress_safe_native(_lz4BufferNative, _textureBufferNative, (int)block.size, _frameBytes);
			Marshal.Copy(_textureBufferNative, _textureBuffer, 0, _frameBytes);

			MemoryStream ms = new MemoryStream(_textureBuffer, 0, _textureBuffer.Length);
			ms.Seek(0, SeekOrigin.Begin);
			System.Drawing.Image x = System.Drawing.Image.FromStream(ms);

			return x;
		
		}

```

And have tried a few different approaches, but i always get 'Parameter is invalid' errors.  What am i missing here?

Thanks you!

**Comment by antithing** [comment]
.. Or is it possible to use SHARPGL (c# opengl wrapper) to display the frames in a wpf application? Thanks again!

**Comment by umetaman** [comment]
@antithing 
The frame textures contained .gv are compressed in DXT1 or DXT5 format.
According to this documentation page System.Drawing.Image supports only GDI+ image file formats.

https://docs.microsoft.com/en-us/dotnet/desktop/winforms/advanced/types-of-bitmaps?view=netframeworkdesktop-4.8

If you use GV, you need to use a library can read DXT1 or DXT5.

**Comment by antithing** [comment]
Thank you! I am now using SharpGL, and it's playing perfectly.  Thanks!
